services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: p2p-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=p2p-transfer
      - PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/transfers
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_DATA_REDIS_HOST=redis_transfer
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=0000

    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres
    container_name: postgres_transfer_db
    environment:
      - POSTGRES_DB=transfers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_transfer
    command: ["redis-server", "--requirepass", "0000"]
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 0000
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
